version: '3.8'
services:
  todo-db:
    image: postgres:15
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: todo-db
    networks:
      - todo-pg
networks:
  todo-pg:
